### PR TITLE
- Add support for reserve-job. Added in beanstalkd 1.12+

### LINKED ISSUE #221: Support for reserve-job
I started adding this but it's not clear what the best way to handle calling the command on pre-1.12 versions.

We're unable to actually catch BAD_FORMAT as it always throws an exception in the connection class.

### PR DESCRIPTION
**Pull request by scottmac**
Before 1.12, we'll return null if this isn't supported.

Fixes #221

### CODE REVIEW

**Comment by SamMousa** [comment]
Shouldn't we throw an exception? Returning null is not optimal for use cases where you reasonably expect it to return a value.

**Comment by scottmac** [comment]
I have no strong opinion on this, happy to change :)

**Comment by SamMousa** [comment]
Let me have a look tomorrow, will get back to you!

**Comment by scottmac** [comment]
Actually, I like that idea.

Also re-throwing an Unknown Command for older versions seems right

**Comment by SamMousa** [comment]
What happens if the response is not found?

Also there seem to be no tests included.

File: src/Contract/PheanstalkInterface.php [hunk 1]
```diff
@@ -153,6 +153,13 @@ public function release(
      */
     public function reserve(): ?Job;
 
+    /**
+     * Reserves/locks a specific job, new in beanstalkd 1.12+
+     *
+     * @param JobIdInterface $job
+     */
+    public function reserveJob(JobIdInterface $job): Job;
```
Comment (SamMousa) [inline src/Contract/PheanstalkInterface.php:161]: Just thinking out loud here...
If we add this to the interface, then any custom implementation of this interface will break.
So should we then, based on this, increase our major version number? Since this becomes a BC breaking release.

(PHPUnit explicitly marks what part of their classes are exempt from their BC promises; we could also do something like this in the future)

Comment (scottmac) [reply src/Contract/PheanstalkInterface.php:161]: Should probably try to solve this for the future as its potential that new commands could be added. Mark this interface as non-BC guaranteed and also bump a new major version?

Comment (SamMousa) [reply src/Contract/PheanstalkInterface.php:161]: If that is the case I will also bump to 7.4.

Alternatively we can version the interface.

Like adding a new protocol1.12 interface that we implement and other implementers can then lag behind.

We could even just have a ReserveJobInterface or something like that... Just thinking out loud, don't go changing all your code unless you think it's the best ;)

Comment (scottmac) [reply src/Contract/PheanstalkInterface.php:161]: beandstalkd repo has a "wait", "put-with-id", "reserve-id" commands listed in issues but no PRs yet.

**Review by SamMousa — APPROVED** [review]

File: src/Pheanstalk.php [hunk 2]
```diff
@@ -258,6 +258,27 @@ public function reserve(): Job
...
+        // New in 1.12, beanstalkd returns BadFormat instead of UnknownCommand
+        try {
+            $response = $this->dispatch(
+                new Command\ReserveJobCommand($job)
+            );
+        } catch (Exception\ServerBadFormatException $e) {
+            throw new Exception\ServerUnknownCommandException();
+        }
+
+        if ($response->getResponseName === ResponseInterface::RESPONSE_BAD_FORMAT) {
```
Comment (SamMousa) [inline src/Pheanstalk.php:275]: This seems to be a typo, `$response->getResponseName` is a function not a property.

More importantly this should be caught by tests. Or even static analysis. (This is for my own todo list #223 )

Comment (scottmac) [reply src/Pheanstalk.php:275]: It's a typo. Test didn't catch it since the __get() on ArrayResponse swallows the warning here and coalesces it to null.

**Review by SamMousa — APPROVED** [review]

**Comment by seth-xdam** [comment]
What's happening with this? I've forked the repository specifically to merge in and use this feature. I'd rather move back to yours, though.

**Comment by SamMousa** [comment]
Apologies, shifting priorities, I'll try to plan some time for this soon

**Comment by seth-xdam** [comment]
Cool. If it helps, we've been using it in production without making any changes besides what's already in this PR. Thanks for your work!

**Comment by SamMousa** [comment]
I'm merging this, but it will only be available in the next major version of this library, just an FYI. 
That version will very likely require PHP8.
